.circleci/config.yml
cmd/sabactl/actions.go
cmd/sabactl/main.go
cmd/sabakan/main.go
crypts.go
ignitions.go
machines.go

- Add http server
- Add options for sabakan

Initialize sabakan project

---

cmd/sabakan/main.go
config.go
crypts_test.go
index.go
index_test.go
machines.go
machines_test.go
query.go
query_test.go

Add POST,PUT,GET /api/v1/machines
- index.go: Indexing structure for search by GET.
- query.go: Query collection using etcd and index.
- Add EtcdWatcher() which execute goroutine to watch etcd. When KV is updated, It will update index.

Add /api/v1/machines

---

Makefile
cmd/sabakan/main.go
crypts.go
machines.go
responses.go

- Add Makefile to develop sabakan
- Add timeout to etcd
- Clean renderer

Improve sabakan

---

Makefile
README.md

Debugging with DHCP client:
```console
$ make debug
$ make connect
```

Add debug task to Makefile

---

.gitignore
client/client.go
client/dhcp.go
client/ipam.go
client/machines.go
cmd/sabactl/dhcp.go
cmd/sabactl/main.go
dhcp.go
dhcp_test.go
docs/api.md
docs/dhcp.md
docs/sabactl.md
docs/schema.md
e2e/sabactl_test.go
ipam.go
model.go
models/etcd/constants.go
models/etcd/dhcp.go
models/etcd/dhcp_test.go
models/etcd/driver.go
models/etcd/ipam_test.go
models/etcd/machine_test.go
models/mock/dhcp.go
models/mock/driver.go
models/mock/ipam.go
web/dhcp.go
web/dhcp_test.go
web/ipam_test.go
web/server.go

Specifications are included in the docs.

[dhcp] Add DHCPConfig

---

.circleci/config.yml

Replace circleci/golang with our own quay.io/cybozu/golang.

Change Go container for CircleCI.

---

docs/getting_started.md
docs/sabakan.md

- sabakan.md: Explain command line usage of the sabakan
- getting_started.md: Add sabakan configuration procedure.

[docs] Add sabakan.md and Update part of getting_started.md

---

.circleci/config.yml
cmd/sabakan/config.go
cmd/sabakan/main.go

If the `-config-file` option is specified, settings is read from the specified file. Otherwise, settings is read from args as before.

add -config-file option

---

docs/api.md
docs/sabactl.md
web/ignitions.go
web/ignitions_test.go

- Update docs.
- Add /api/v1/ignitions/ROLE/ID in sabakan for sabactl ignitions cat.

Design sabactl subcommands for ignition templates

---

client/ignitions.go
cmd/sabactl/ignitions.go
cmd/sabactl/main.go
docs/sabactl.md
e2e/sabactl_test.go

This PR implements sabactl ignition commands:
- sabactl ignitions get ROLE
- sabactl ignitions cat ROLE ID
- sabactl ignitions set ROLE
- sabactl ignitions delete ROLE ID

Implement sabactl ignitions commands

---

docs/api.md
ignition.go
ignition_test.go
models/etcd/ignition.go
web/coreos.go
web/ignitions.go
web/ignitions_test.go

Fix ValidateIgnitionTemplate() to replace test variables

---

cmd/sabakan/config.go
cmd/sabakan/main.go
docs/api.md
docs/sabakan.md
web/apierror.go
web/crypts_test.go
web/dhcp_test.go
web/ignitions_test.go
web/image_test.go
web/ipam_test.go
web/machines_test.go
web/main_test.go
web/server.go
web/server_test.go

API access control denies APIs affecting the resources from remote
hosts.

REST API access controll

---

client/status.go

- Error messages are like:
- Error: Server returned 400 Bad Request, invalid request: invalid bmc-ipv4-range-mask
- Error: Server returned 404 Not Found, requested resource is not found
- Error: Server returned 409 Conflict, conflicted
- Error: Server returned 500 Internal Server Error, (err.Error())

[sabactl] Show reason when http status code is [400,600)

---

docs/api.md
docs/machine.md
ipam.go
ipam_test.go
machines.go
models/etcd/index.go
models/etcd/machine_test.go
query.go
query_test.go
testdata/test/networkd/10-node0.netdev
web/ignitions_test.go

[machine] Replace Network field with IPv4 and IPv6

---

client/client.go
client/crypts.go
cmd/sabakan-cryptsetup/main.go
cmd/sabakan-cryptsetup/storage.go
docs/api.md
docs/disk_encryption.md
docs/sabakan-cryptsetup.md
web/crypts_test.go
web/server.go
web/server_test.go

- It requires sabakan server.
- sabakan-cryptsetup initialize target disk(by-path) as encrypted disk.
- target disk is decrypted by cryptsetup if encryption key exists on sabakan.

sabakan-cryptsetup implementation

---

client/ignition_template.go
client/ignition_template_test.go
testdata/base/base.yml
testdata/test/systemd/bird.service
testdata/test/test.yml

- Change "source" to "name".
- Support "mask".
- If "mask: true", then sabactl does not load service file.

[ignitions] Update input yaml format

---

client/assets.go
client/client.go
client/crypts.go
client/dhcp.go
client/ignitions.go
client/images.go
client/ipam.go
client/logs.go
client/machines.go
client/status.go
cmd/sabactl/ignitions.go
cmd/sabactl/logs.go
cmd/sabactl/main.go
e2e/main_test.go
e2e/sabactl_test.go
models/etcd/asset.go
models/etcd/dhcp.go
models/etcd/ignition.go
models/etcd/image.go
models/etcd/ipam.go
models/etcd/machine.go
models/etcd/storage.go

This series of commits implement audit logging in etcd driver,
and `sabactl log` sub command with e2e tests.

Record audit logs on etcd

---

.circleci/config.yml
cmd/sabakan/config.go
cmd/sabakan/main.go
docs/getting_started.md
docs/sabakan.md
e2e/main_test.go
models/etcd/main_test.go
mtest/user-data.yml

- Change `-etcd-servers` to `-etcd-endpoints`.

[etcdutil] Use external package to refactor etcd config and client

---

.circleci/config.yml
cmd/sabakan/main.go
mtest/Makefile

https://github.com/cybozu-go/etcdutil/pull/3

change etcd TLS config

---

docs/api.md
docs/lifecycle.md

- Add API PUT,DELETE /api/v1/labels.
- Add new states Uninitialized and Updating.

Update api.md and lifecycle.md

---

CHANGELOG.md
docs/api.md
docs/graphql.md
docs/sabakan.md
gql/generated.go
gql/gqlgen.yml
gql/match.go
gql/match_test.go
gql/models_gen.go
gql/resolver_impl.go
gql/schema.graphql
gql/types.go
machines.go
web/machines_test.go

* Remove stub implementation of MachineState enum.
* Add MachineSpec to the schema for better struct mapping.

Improve GraphQL implementation

---

client/aliases.go

Aliases for the following two types are added to this pacakge.
* sabakan.ImageIndex
* sabakan.IgnitionInfo

[client] add alias types from sabakan

---

docs/ignition.md
ignition.go
ignition_test.go

This PR adds `json` function to render objects in JSON for ignition templates.

[ignition] add json rendering function.

---

RELEASE.md
docs/ignition.md
ignition.go
models/etcd/convert2.go
models/etcd/schema.go
temlate_funcs.go
template_funcs.go
template_funcs_test.go

This PR adds arithmetic functions for Ignition templates.
Other changes to be included are:
* Initialization of schema version.
* Make Ignition template meta data API better.

Arithmetic functions for Ignition templates, et al.

---

docs/lifecycle.md
machines.go
web/state_test.go

Add state transitions as follows.
- Unhealthy to Healthy
- Unhealthy to Unreachable
Remove state transitions as follows.
- Unhealthy to Uninitialized
- Unreachable to Uninitialized

Refine sabakan machines state

---

README.md
bin/env

Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

Add the text link to Quay.io

---

CHANGELOG.md
version.go

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

Bump version to 2.5.2

---

pkg/sabakan-cryptsetup/cmd/tpm.go

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

Update comments for nilerr.

---

mtest/.gitignore
mtest/Makefile
mtest/cluster.yml
mtest/netboot.go

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

Use Flatcar in mtest.

---

mtest/Makefile

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

use flatcar's container-linux-config-transpiler

---

mtest/Makefile

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

fix transpiler's download url

---

.gitignore
Makefile
e2e/main_test.go
models/etcd/main_test.go
mtest/Makefile

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

Refactor tools utilization

---

pkg/sabakan-cryptsetup/cmd/tpm.go

Signed-off-by: binoue <banji-inoue@cybozu.co.jp>

Fix sabakan-cryptsetup for TPM 1.2

---

mtest/Makefile
mtest/cluster.yml
mtest/host-ign.yml

Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

Apply placemat v2

---

.github/workflows/main.yaml
.github/workflows/release.yaml
go.mod
mtest/tools_test.go

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

update golang to 1.17

---

docs/getting_started.md
docs/machine.md

ref: #225 #226 
Signed-off-by: kouki <kouworld0123@gmail.com>

Fix some example values in the documentation.

---

web/asset.go

Increase maxAssetSize to 4GiB

---

CHANGELOG.md
version.go

Bump version to 2.9.1

---

models/etcd/dhcp.go
models/etcd/dhcp_test.go

Fix DHCP renew

---

models/etcd/dhcp.go

Fix updating lease

---

CHANGELOG.md
version.go

Bump version to 2.9.2

---

metrics/collector.go
metrics/collector_test.go

Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>

remove machine status metrics when the machine is removed

---

models/mock/image.go

Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>

Use copy() instead of loop

---

README.md
client/ignition_template.go
client/ignition_template_test.go
docs/concepts.md
go.mod
go.sum
models/etcd/convert3.go
mtest/Makefile
web/ignition_render.go
web/ignition_render_test.go

part of https://github.com/cybozu-go/neco/issues/2082.
Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

Rename flatcar-linux to flatcar

---

mtest/Makefile
mtest/cluster.yml
mtest/netboot_test.go

This PR fixes following issue
- https://github.com/cybozu-go/sabakan/issues/271

re-enable vTPM

---

CHANGELOG.md
RELEASE.md
version.go

update version to v3.0.0 and fix document.

Bump version to v3.0.0

---

models/etcd/asset_updater.go

This PR fixes these issue
- https://github.com/cybozu-go/sabakan/issues/269
Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>

fix dupulicate assets url

---

pkg/sabakan/main.go

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

fix error message for advertise-url-https

---

CHANGELOG.md
version.go

Bump version to 3.1.3
See-also: https://github.com/cybozu-private/neco-tasks/issues/317

Bump version to 3.1.3

---

CHANGELOG.md
version.go

See-also: https://github.com/cybozu-private/neco-tasks/issues/598

Bump version to 3.1.6
