cmd/sabakan/main.go, config.go, responses.go
- sabakan command line options which are used on the IP adddress
calculation of the machine registration is saved in the etcd for
distributing other etcd members. sabakan daemon requires only listen
address and etcd connection parameters.
- Delete initHello() as sample handler.
=> Add config.go and delete sample functions in sabakan/main.go

.circleci/config.yml, cmd/sabakan/main.go, config.go, crypts.go, crypts_test.go, main_test.go, responses.go, responses_test.go
**What this PR does**
Implement the following API
- GET `/crypts/<serial>/<path`
- DELETE `/crypts/<serial>`
- POST `/crypts/<serial>`
---
Let all response Content-Type are `application/json`.
Add crypt key for the encrypted disk.
```json
{"path": <path>,"key": <key>} 
```
- status code : 201 Created
- response body 
- ```json
{"path": <path>, "key": <key>}
```
- invalid params (400)
- `/<prefix>/crypts/<serial>/<path>` already exists in etcd (400)
```console
$ curl -i -X POST \
-H "Content-Type:application/json" \
-d \
'{"key": "key101", "path":"aaaaa"}' \
'http://localhost:8888/api/v1/crypts/1'
HTTP/1.1 201 Created
Content-Type: application/json
Date: Tue, 10 Apr 2018 09:12:12 GMT
Content-Length: 31
{"path":"aaaaa","key":"key101"}
```
---
Get specific crypts key.
- 200 OK
- response …
=> Crypts API

crypts.go, crypts_test.go, responses_test.go
Disk encryption keys are likely binary data.
sabakan should accept them.
Changes:
* Replace POST handler with PUT to accept binary keys.
* Change GET response to send binary key.
* Simplify DELETE implementation.
* Fix TOCTTOU bug in DELETE.
* Rewrote tests.
=> Allow binary data for disk encryption keys.

cmd/sabakan/main.go, e2e/sabactl_test.go, model.go, models/etcd/dhcp.go, models/etcd/dhcp_test.go, models/etcd/driver.go, models/etcd/index.go, models/etcd/ipam.go, models/etcd/ipam_test.go, models/etcd/machine.go, models/etcd/machine_test.go, models/etcd/main_test.go, models/etcd/storage_test.go, models/etcd/watch.go, models/mock/dhcp.go, models/mock/driver.go, models/mock/ipam.go, web/dhcp.go, web/dhcp_test.go, web/ipam.go, web/ipam_test.go
* retrieve the revision first of all, and use it as the start revision of watch.
* wait for driver to complete initialization before serving requests.
* watch for modification of configs and atomically update pointers to them.
* change API to return non-nil error if a config is nil.
=> [etcd] revamp watch implementation.

cmd/sabactl/machines.go, docs/api.md, docs/sabactl.md, docs/schema.md, e2e/sabactl_test.go, machines.go, models/etcd/index.go, models/etcd/index_test.go, query.go, web/machines.go, web/machines_test.go
- sabactl supports `--bmc-type` in `sabactl machines get`
- sabakan API supports `bmc-type` query parameter in GET`/api/v1/machines`
- BMC Type in the Machine is mandatory and supports `iDRAC-9` and `IPMI-2.0`.
=> Add BMC Type to Machine

cmd/sabakan/config.go, cmd/sabakan/main.go, docs/sabakan.md, models/etcd/watch.go
etcd can be protected by enabling user authentication.
To access such an instance, sabakan need to have configuration options for etcd authentication.
This commit adds these two:
* `etcd-username`: username for etcd auth.
* `etcd-password`: password for etcd auth.
=> [etcd] add username and password options

docs/sabakan.md
API access control denies APIs affecting the resources from remote
hosts.
=> Describe API access control

cmd/sabakan/main.go, models/etcd/constants.go, models/etcd/dhcp.go, models/etcd/dhcp_test.go, models/etcd/driver.go, models/etcd/ignition.go, models/etcd/image.go, models/etcd/image_test.go, models/etcd/image_updater.go, models/etcd/index.go, models/etcd/ipam.go, models/etcd/ipam_test.go, models/etcd/machine.go, models/etcd/machine_test.go, models/etcd/main_test.go, models/etcd/node_index.go, models/etcd/storage.go, models/etcd/watch.go
This Pull Req. contains the following refactors:
- Using etcd [namespace](https://godoc.org/github.com/coreos/etcd/clientv3/namespace) instead of `prefix` variable
- Using GetResponseTxn instead of internal protobuf.
=> Refactor on etcd client

cmd/sabakan/config.go, cmd/sabakan/main.go
* sabakan's etcd prefix should have `/` at the end.
* When connecting to etcd failed, sabakan should be terminated with an error.
=> fix sabakan prefix

cmd/sabactl/machines.go, cmd/sabactl/sabactl_completion.bash, docs/api.md, docs/sabactl.md
- Add --role option in sabactl machines get.
- Remove index-in-rack from api.md because of no implementation.
- Order sabactl machines get option in sabactl.md.
=> Fix not matched between implements and documents

web/coreos.go
- Default scheduler is mq-deadline.
- virtio attached machine is ignored its parameter because
the virtio_scsi force enables use_blk_mq by scsi driver.
- Expected is that both of Physical machine and Virtual machine use
the mq-deadline.
=> Enable multi-queue I/O scheduler for netboot hosts

audit.go, docs/api.md, docs/audit.md, docs/sabactl.md, docs/schema.md, model.go, models/etcd/constants.go, models/etcd/driver.go, models/etcd/log.go, models/etcd/log_test.go, models/mock/driver.go, models/mock/ipam.go, models/mock/log.go, web/logs.go, web/logs_test.go, web/server.go, web/server_test.go
This series of commits implements an audit logging framework for sabakan.
It does not yet record logs nor implement `sabactl log` subcommand.
They will be implemented in another pull request.
=> Audit logging framework

cmd/sabakan-cryptsetup/storage.go, cmd/sabakan-cryptsetup/storage_test.go
Using by-path name is more strict and convenient to manage devices automatically.
=> Use by-path instead of real path on dev mapper

models/etcd/image_updater.go
When deleting an image by `sabactl images delete`, the images are remaining on the local disk.
```console
$ sabactl images upload 100.000 kernel initrd
$ sabactl images delete 100.000
$ sabactl images index
[
{
"id": "1745.5.0",
"date": "2018-07-17T22:02:03.097669114Z",
"urls": [
"http://10.69.0.3:10080/api/v1/images/coreos/1745.5.0",
"http://10.69.0.195:10080/api/v1/images/coreos/1745.5.0",
"http://10.69.1.131:10080/api/v1/images/coreos/1745.5.0"
],
"exists": true
}
]
$ sudo ls /var/lib/sabakan/images/coreos/
100.000  1745.5.0
```
=> Fix remaining deleted image bug

models/etcd/asset_updater.go, models/etcd/watch_stateful.go, models/etcd/watch_stateful_test.go, mtest/Makefile, mtest/assets_test.go, mtest/env.go, mtest/run_test.go
Assets monitors etcd changes statefully by storing the last watched
revision in the filesystem.  When etcd compacted the database while
sabakan is stopping, sabakan would not be able to resume the stateful
watch from the saved revision.
In this case, sabakan resets the revision stored in the filesystem
to zero and re-synchronize all assets with the current database.
Unfortunately, sabakan could generate corrupted revision file
because it did not truncate the revision file.  This commit
truncates the revision file properly, and adds unit tests for them.
=> [assets] fix infinite loop upon etcd compaction.

client/kernel_params.go, cmd/sabactl/kernel_params.go, cmd/sabactl/kernerl_params.go, cmd/sabactl/main.go, dhcpd/discover.go, docs/api.md, docs/getting_started.md, docs/sabactl.md, docs/schema.md, kernel_params.go, kernel_params_test.go, model.go, models/etcd/constants.go, models/etcd/driver.go, models/etcd/kernel_params.go, models/mock/driver.go, models/mock/kernel_params.go, mtest/netboot_test.go, web/coreos.go, web/coreos_test.go, web/kernel_params.go, web/kernel_params_test.go, web/main_test.go, web/server.go
ハードコードされているiPXE scriptのKernel parameterを変更できるようにしました。
- sabakanにkernel paramsを登録・取得するためのAPIを追加
- etcdにkernel paramsを登録・取得するための処理を追加
- etcdにkernel paramsのデータスキーマを仕様を決定
- sabactlにkernel paramsを登録・取得するコマンドを追加
- iPXEブート時に登録されたkernel paramsを含めてiPXE scriptの生成
=> Add kernel parameters support

client/ignitions.go, cmd/sabactl/assets.go, cmd/sabactl/ignitions.go, cmd/sabactl/map_flags.go, docs/api.md, docs/ignition.md, docs/schema.md, e2e/sabactl_test.go, ignition.go, ignition_test.go, model.go, models/etcd/constants.go, models/etcd/ignition.go, models/etcd/ignition_test.go, models/mock/ignition.go, web/coreos.go, web/coreos_test.go, web/ignitions.go, web/ignitions_test.go
* add `-meta` options to `sabactl ignition set` subcommand.
* add metadata in request header of put ignitions template API.
* add `Metadata` function to render ignitions template.
=> store metadata for ignitions template

machines.go, machines_test.go
For integration with CKE, machine labels are need to be valid
as the same way as Kubernetes.  The role value also need to be
vaild label value.
Kubernetes syntax is described at
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
=> Validate label names and values samely as Kubernetes

pkg/sabactl/cmd/ignitions.go
Fix following error
```
$ sabactl ignitions cat
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/cybozu-go/sabakan/pkg/sabactl/cmd.glob..func10(0xc409e0, 0xc6b4d8, 0x0, 0x0, 0x0, 0x0)
/work/pkg/sabactl/cmd/ignitions.go:73 +0x12c
github.com/spf13/cobra.(*Command).execute(0xc409e0, 0xc6b4d8, 0x0, 0x0, 0xc409e0, 0xc6b4d8)
/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc43e20, 0xc00023df88, 0x407440, 0xc000074058)
/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc43e20, 0x0, 0x0)
/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/cybozu-go/sabakan/pkg/sabactl/cmd.Execute()
/work/pkg/sabactl/cmd/root.go:65 +0x31
main.main() …
```
=> Fix sabactl ignitions command error

client/ignition_template.go, client/ignition_template_test.go, docs/api.md, docs/getting_started.md, docs/ignition_template.md, docs/sabactl.md, testdata/base/base.yml, testdata/test/test.yml
Ignition can download file contents from remote servers.
This commit enhances ignition template YAML to use this feature
by adding "remote_files" directive.
=> [ignition] add "remote_files" to template.

client/ignition_template.go, client/ignition_template_test.go, docs/ignition_template.md, mtest/ignitions/files/etc/hostname, mtest/ignitions/systemd/foo.service, mtest/ignitions/worker.yml, testdata/base/base.yml
Sabakan 2.0.0 degraded ignition template system due to missing
mandatory properties for files such as "filesystem" or "mode".
That was not tested in multi-host test.
This commit fixes the degradation and add tests for them.
=> [ignition] add mandatory properties for files

mtest/netboot_test.go
`,` is not allowed to separate options.  A white space is.
=> [mtest] fix wrong kernel boot option

gql/resolver_impl.go, models/etcd/machine.go
Also, show graphql request log.
=> [audit] No longer record state transition

go.mod
This PR fixes the sabakan-cryptsetup failure that occurs on TPM enabled environment.
=> Update go-tpm to 0.3.2

docs/lifecycle.md, machines.go, web/state_test.go
Allow following state transitions.
- Unhealthy --> Updating
- Unreachable --> Updating
- To restart Unhealthy, Unreachable equipment using Updating state.
- Unreachable --> Unhealthy
- If Unhealthy equipment temporarily becomes Unreachable, it will be stuck in the Unreachable state
- Uninitialized --> Unhealthy
- Uninitialized --> Unreachable
- To prevent Unhealthy or Unreachable equipment from getting stuck in the Uninitialized state after a state transition from Updating to Uninitialized. 
- If this change is made, it could cause an immediate transition from Uninitialized to Unhealthy or Unreachable. This is temporary and I see no problem as it will be pulled back to the correct state by the external controller.
Signed-off-by: kouki <kouworld0123@gmail.com>
=> Allow some state transitions.

CHANGELOG.md, models/etcd/watch_stateful.go, models/etcd/watch_stateless.go
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>
=> Fix to check error of etcd watch response

README.md, docs/getting_started.md
Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>
=> update document for sabakan TLS

.github/workflows/release.yaml
The `gh` command requires any one of a `GH_REPO` environment variable,
a `--repo` option, or a local git repository.
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>
=> Fix release workflow to run on git repository
